### ISSUE TITLE
Default No Selected Smile

### ISSUE THREAD

**Issue by naveedali** [sujithkanna/SmileyRating#10]
I want Rating bar to have no selected rating in the start..
let me know if rating bar has this functionality

**Comment by sujithkanna** [comment]
Currenty the functionality is not there, But will make it sooner. Thank you :)

**Comment by kewal07** [comment]
Definitely require this. Great ratings bar. Thanks

**Comment by vitusya** [comment]
+1

**Comment by sujithkanna** [comment]
SmileyRating has been updated, Now by default, the rating will be set to NONE. You have to tap on any snimey to select.
*Drag won't work if NONE selected*
Use this dependency
```gradle
compile 'com.github.sujithkanna:smileyrating:1.6.6'
```
If you want to set the smiley to NONE programmatically, use one of the below methods.
```java
mSmileRating.setSelectedSmile(SmileRating.NONE); // Without animation
mSmileRating.setSelectedSmile(SmileRating.NONE, true); // With animation
```
Thank you!

**Comment by paulomcnally** [comment]
@NaveedALi close this :)

**Comment by naveedali** [comment]
thanks man :)

**Comment by dineshkanagaraj** [comment]
hi sir i want to place the good smile first and terrible at last ...how to do that

**Comment by sujithkanna** [comment]
You cannot switch the positions of the Smileys. Maybe we will introduce that option in future. Thank you!
