### ISSUE TITLE
How to set custom font for textSelection and textNonSelection

### ISSUE THREAD

**Issue by Feroz-Istar** [sujithkanna/SmileyRating#12]
How to set custom font for textSelection and textNonSelection

**Comment by sujithkanna** [comment]
That is currently not possible since the textSelection is transformed to textNonSelection (color,size). Can't transform one typeface to another. but you can set custom typeface for all text
```java
mSmileRating.setTypeface(yourTypeface);
```
Really sorry for unable to help you in this. Thank you!
