### ISSUE TITLE
Default none selected

### ISSUE THREAD

**Issue by paulomcnally** [sujithkanna/SmileyRating#15]
Allow none selected default? 

For example star on google play:

![Google Play](http://i.imgur.com/A7CdFWm.png)

**Comment by sujithkanna** [comment]
Currently, I am planning to refactor code to make more features, This I included in that task, surely I will release the updated ratingbar sooner.

**Comment by sujithkanna** [comment]
SmileyRating has been updated, Now by default, the rating will be set to NONE. You have to tap on any snimey to select.
*Drag won't work if NONE selected*
Use this dependency
```gradle
compile 'com.github.sujithkanna:smileyrating:1.6.6'
```
If you want to set the smiley to NONE programmatically, use one of the below methods.
```java
mSmileRating.setSelectedSmile(SmileRating.NONE); // Without animation
mSmileRating.setSelectedSmile(SmileRating.NONE, true); // With animation
```
Thank you!

**Comment by vitusya** [comment]
if mSmileRating.setSelectedSmile(SmileRating.NONE); 
and then on first selection select Great, Great disappears
