### ISSUE TITLE
Disable click

### ISSUE THREAD

**Issue by paulomcnally** [sujithkanna/SmileyRating#20]
How to disallow click?

`
android:clickable="false"
android:focusable="false"
`

android:clickable setted false don't work.

![Imgur](http://i.imgur.com/L37qjmc.png)

**Comment by angelisimo** [comment]
Hey, same issue here.

Even creating the element as docs says it won't  trigger the listeners:
smileRating.setSelectedSmile(BaseRating.GREAT, false);

It's still accepting clicks and animation

Thank you.

**Comment by sujithkanna** [comment]
I made the API for this feature. Sorry I couldn't give it sooner because of some unexpected reasons. t is fixed in a38995b5be3cd55cce9d213f773f32b25c52301e commit. Thank you :)

**Comment by addisonElliott** [comment]
As a polite reminder, this can be closed since support for isIndicator has already been added.
