### ISSUE TITLE
Smile new doesn't show

### ISSUE THREAD

**Issue by EstebanC02** [sujithkanna/SmileyRating#22]
Hi guys! You are making such a great job, i really like your library. I am detect an issue when is select the New Smile, it doesn't show it. Also doesn't show when the smileRating.setSelectedSmile is loaded.

Android version: 5.1.1
Model number: SM-J120M
compile 'com.github.sujithkanna:smileyrating:1.6.7'

![screenshot_2017-07-09-17-43-16-1-min](https://user-images.githubusercontent.com/11792308/27998227-960ed270-64cf-11e7-992e-15fa65d96170.png)

But when i select another Smile and come back with the New, in that case it is show it

![screenshot_2017-07-09-17-43-02-1-min](https://user-images.githubusercontent.com/11792308/27998234-d997968a-64cf-11e7-8ed6-b70ac6da6ad5.png)

![screenshot_2017-07-09-17-43-05-1-min](https://user-images.githubusercontent.com/11792308/27998237-ea44a4c8-64cf-11e7-830a-eeb79359613e.png)

**Comment by sujithkanna** [comment]
Thank you for the fixTh @addisonElliott , Your fix worked very well. @EstebanC02 , use the updated version of the SmileyRating. Thank you!
