### ISSUE TITLE
 Unselect smiley on rating is sent

### ISSUE THREAD

**Issue by rupbhangale** [sujithkanna/SmileyRating#26]
I want to unselect smiley on rating is sent.
I used smileRating.setSelectedSmile(BaseRating.NONE); which worked but after using this functionality angryColor do not reflect and BaseRating.GREAT animation is not working fine.

Please suggest any solution for the same.

**Comment by addisonElliott** [comment]
Go around and check out issue #22 and issue #24 and see if these apply to you.

If so, I just submitted pull requests to fix the issues and we are waiting on the owner to check/accept them.

**Comment by sujithkanna** [comment]
@rupbhangale , It is fixed now, kindly use the new version of Smileyrating. Thank you!
