### ISSUE TITLE
Change text 

### ISSUE THREAD

**Issue by selini** [sujithkanna/SmileyRating#42]
Hello, 

first of all thanks for the great library, it is really helpful.
I want to ask if it is possible to change the text under the faces.

Thanks!

**Comment by shining-cat** [comment]
Hello, it is possible : [see Readme](https://github.com/sujithkanna/SmileyRating#you-can-change-the-smiley-name-also)

**Comment by selini** [comment]
Thanks you very much! I did not see it.  I will close the issue
