### ISSUE TITLE
Clearing the smiley selection.

### ISSUE THREAD

**Issue by sivansundar** [sujithkanna/SmileyRating#46]
Hi @sujithkanna.

First of all, this is a really good library. Using this for a college project and I guess i'll surely use this in the future. Coming to the problem I faced, I wanted to clear the selection after a button click and I couldn't get that to work. Even after reading the documentation I couldn't find a way around this. After playing around for a while, the easiest way to acomplish this would be to set the setSelectedSmiley() function to -1, i.e, `smileyRating.setSelectedSmiley(-1);` 

Doing this cleared the selection off. This could be handy when it comes to submitting a survey or a rating in general and you would want to clear the selection after submission. 

Just wanted to raise a solution/info. 
Thanks for the cool library. Cheers (y)

**Comment by cybkw** [comment]
that's great

**Comment by jonyluke** [comment]
Not working for me.

**Comment by jonyluke** [comment]
smileRating.setSelectedSmile(BaseRating.NONE);
