### ISSUE TITLE
setNameForSmile returns null object Reference

### ISSUE THREAD

**Issue by kev7037** [sujithkanna/SmileyRating#47]
Hi.
I'm trying to change name of Smiles and it throws null object reference;
here is my code in a fragment.

```
final RatingDiaglogClass ratingDiaglogClass = new RatingDiaglogClass(contextHolder, R.style.RatingDialogTheme);
LayoutInflater inflater = (LayoutInflater) contextHolder.getSystemService(Context.LAYOUT_INFLATER_SERVICE);
View dv = inflater.inflate(R.layout.layout_rating_dialog, null);

ratingDiaglogClass.setContentView(dv);

final SmileRating smileRating = view.findViewById(R.id.smile_rating);
smileRating.setNameForSmile(BaseRating.BAD, "sthElse");

ratingDiaglogClass.show();
```

This is the error:

> Attempt to invoke virtual method 'void com.hsalf.smilerating.SmileRating.setNameForSmile(int, java.lang.String)' on a null object reference

**Comment by addisonElliott** [comment]
It's been awhile since I've used this library, but as a sanity check, make sure that smileRating is not null first. If it is null, then you're not getting the right view.

**Comment by addisonElliott** [comment]
@kev7037 What's the status on this issue? Did you resolve it?

**Comment by kev7037** [comment]
Yes, I was using it inside a fragment and there was a problem about using views and not about the library. thanks for your useful reply.

One more thing. While I was testing the app on 4K screen device Sony Xperia XZ Premium, while inflating on a fragment, part of the layout wont show up.

![photo_2018-12-21_22-13-32](https://user-images.githubusercontent.com/27485656/50358348-3679bc80-056e-11e9-8fa6-8ca965e7a928.jpg)

**Comment by sujithkanna** [comment]
It should not be a problem now. We have released a new version of the library with all the fixes. So it is advised to use the latest classes and apis
