### ISSUE TITLE
Set color individually for a smiley

### ISSUE THREAD

**Issue by jonyluke** [sujithkanna/SmileyRating#48]
The only smiley color you can change individually is the angry one.
`smileyRating.setAngryColor(int color);`

The other option is to change all the color of all smileys except Angry/Terrible smiley.
`smileRating.setNormalColor(int color);`

Is there a way to change individually other smiley, like great smiley?

**Comment by sujithkanna** [comment]
You can do it now simply. Update to the new version. Apis also changed. Old classes have been removed. The integration will be easy with this version.
