### ISSUE TITLE
Attribute to change line color

### ISSUE THREAD

**Issue by dgadelha** [sujithkanna/SmileyRating#6]
Hello and thanks again for such a great library. I'm loving it!

I think a missing feature is one to allow to change the line color, that one:

![Screenshot](https://gadeco.azurewebsites.net/f/2017-03-29_18-59-35.png)

Something like `app:lineColor="#FF000000"` would be awesome.

Thanks!

**Comment by sujithkanna** [comment]
The placeHolder smiley's color and line color has to be equal. That will look good, So I made the color of the placeholder smile color and line color. 
Check this commit 6305eaafe9360254e7d1ce0b6fc1783f241d1f8f
Tell me if it is ok and makes sense. :) If ok I will publish updated version :)

**Comment by dgadelha** [comment]
Hi

I asked that because would be a bit nicer to have the ability to hide the line (`app:lineColor="@android:color/transparent"`). I asked this way because it would also allow some other people to set their own color, instead of the ability of only to hide the line.

Thanks!

**Comment by sujithkanna** [comment]
Thats a good option :) but different color for placeholder and line wont look nice. But hiding the line is a good option. I can give api to hide line. Is that ok???

**Comment by dgadelha** [comment]
Would look good, thanks!

**Comment by sujithkanna** [comment]
The api has been implemented and new version has been released. I hope it is not too late. Thank you!

**Comment by dgadelha** [comment]
You're always quick, thanks for such assistive support!
