### ISSUE TITLE
Casting error

### ISSUE THREAD

**Issue by niish03** [sujithkanna/SmileyRating#64]
I got an casting error in
        smileRating = findViewById(R.id.smile_rating);
while i tried manually casting too by replacing
        smileRating = (SmileRating)findViewById(R.id.smile_rating);

please provide me an solution

**Comment by sujithkanna** [comment]
I think you are using version 2 of SmileyRating where we corrected the typo of the first version.

So instead of `SmileRating` use `SmileyRating`

**Comment by niish03** [comment]
Thank you really it really helped me and i got the perfect output.
