### ISSUE TITLE
Rating reset on keyboard open

### ISSUE THREAD

**Issue by haris4063** [sujithkanna/SmileyRating#7]
I have multiple smileyrating bars and edittexts in my view. after selecting smileys on ratingbars when i try to enter text in edittext, all ratingbars reset to default smiley. 

![videotogif_2017 03 30_15 28 33](https://cloud.githubusercontent.com/assets/4163398/24500894/c752e5f6-1560-11e7-9bd3-fe3771f2295d.gif)

**Comment by sujithkanna** [comment]
Oopsy! I will check the issue and will give you a proper fix :) Thank you!

**Comment by sujithkanna** [comment]
Issue has been solved. Check the commit hash for the changes 8bb79effff10ff577a36e399bc8dc94111df72f7

use 
```groovy
compile 'com.github.sujithkanna:smileyrating:1.6.2'
```

Hope this solves the issue :)

**Comment by haris4063** [comment]
thanks for quick response. I am using forked version of your repo, kindly tell me the change in code

**Comment by sujithkanna** [comment]
https://github.com/sujithkanna/SmileyRating/commit/8bb79effff10ff577a36e399bc8dc94111df72f7

Here it will show the line I changed. make the exact same change in notifyListener method.

**Comment by haris4063** [comment]
thanks
